name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install -r requirements.txt

          dvc repro

          echo '## CML Report' > report.md
          ((dvc metrics diff --show-md master) || echo '') >> report.md
          ((dvc plots diff --target loss.csv --show-vega master > vega.json && vl2png vega.json | cml-publish --md) || echo '') >> report.md
          cml-pr --md 'dvc.lock' '.gitignore' loss.csv metrics.json >> report.md
          cml-send-comment report.md  
          